QADoorWebDjango/QADoorWebDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('QADoorWebDjangoApp.urls')),
]

QADoorWebDjango/QADoorWebDjangoApp/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page
from . import views

app_name = 'QADoorWebDjangoApp'
urlpatterns = [
    url(r'^$', views.question_index, name='index'),
    url(r'^detail/(?P<question_id>\d+)$', cache_page(60 * 15)(views.question_detail), name='detail'),
    url(r'^search/$', views.question_search, name='search'),
    url(r'^tag/(?P<tag_name>.+)$', views.question_tag, name='tag'),
]

QADoorWebDjango/QADoorWebDjangoApp/models.py
# from django.db import models
from mongoengine import *
from QADoorWebDjango.settings import DBNAME

connect(DBNAME)

# Create your models here.
class Questions(Document):

    _id = IntField(primary_key=True)
    url = URLField()
    title = StringField()
    content = StringField()
    is_solved = BooleanField(default=0)
    answer_count = IntField()
    view_count = StringField()
    vote_count = StringField()
    tags = ListField()
    answers = ListField()
    source = StringField()

    meta = {'collection': 'questions'}  # 指明连接数据库的哪张表


# for i in Questions.objects[:10]:  # 测试是否连接成功
#     print(i._id)

QADoorWebDjango/QADoorWebDjangoApp/views.py
from django.shortcuts import render, redirect
from .models import Questions
# from django.core.paginator import Paginator

def question_index(request):
    questions = Questions.objects
    context = {
        'questions': questions,
    }
    return render(request, 'QADoorWebDjangoApp/index.html', context)

def question_tag(request, tag_name):
    questions = Questions.objects.filter(tags=tag_name)
    context = {
        'questions': questions,
    }
    return render(request, 'QADoorWebDjangoApp/index.html', context)


def question_search(request,):
    search_for = request.GET['search_for']
    if search_for:
        questions = Questions.objects.filter(title__icontains=search_for)
        context = {
            'questions': questions,
        }
        return render(request, 'QADoorWebDjangoApp/index.html', context)
    else:
        return redirect('app:index')


def question_detail(request, question_id):
    question = Questions.objects.filter(_id=question_id).first()
    return render(request, 'QADoorWebDjangoApp/detail.html', {'question':question})


def not_found(request, error):
    return render(request, 'QADoorWebDjangoApp/404.html')

QADoorWebDjango/QADoorWebDjangoApp/templates/QADoorWebDjangoApp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'css/materialize.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>


    <title>问答门</title>
</head>
<body>

    <nav>
        <div class="nav-wrapper container col s8 m8 l8">
          <ul class="hide-on-med-and-down">
            <li><a href="{% url 'QADoorWebDjangoApp:index' %}">问答门</a></li>
          </ul>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li>
                <form id="search_form" class="col s12" action="/search/" method="get">
                  <div class="row">
                    <div class="input-field col s6">
                      <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                      <input id="search" type="text" value="" name="search_for">
                    </div>
                  </div>
                </form>
              </li>
              <li><a href="/">问答</a></li>
              <li><a href="/">专栏</a></li>
              <li><a href="/">求职</a></li>
          </ul>
        </div>
    </nav>

    <div class="container">
         <div>
            {% block content %}
            {% endblock %}
         </div>

    </div>

    <footer class="page-footer">
      <div class="footer-copyright">
        <div class="container">
        © 2017 Copyright Jlan
        </div>
      </div>
    </footer>

    <script>
      $(document).ready(function() {
        $(".button-collapse").sideNav();
      });

      <!--$(function() {
          $('#search').bind('input propertychange', function () {
              var $key = $("#search").val();
              $("#search_form").attr("action",'/search/'+$key+'/');
          })
      });-->
    </script>

</body>
</html>

QADoorWebDjango/QADoorWebDjangoApp/templates/QADoorWebDjangoApp/detail.html
{% extends "QADoorWebDjangoApp/base.html" %}

{% block content %}

  <div class="row">
        <div class="col s12 m12">
          <h2 class="header">{{ question.title| safe }}</h2>
          <div class="card">
            <div class="card-action">
              <div class="article-meta">
                {# 文章标签 #}
                <i class="material-icons">label</i>
                {% for tag in question.tags %}
                  <div class="chip">
                    <a href="{% url 'QADoorWebDjangoApp:tag' tag %}">{{tag}}</a>
                  </div>
                {% endfor %}
              </div>
            </div>

            <div class="card-content">
                <hr>
                <p>{{ question.content | safe }}</p>
            </div>

            <div class="card-action">
                来源：<a class="mdl-button" href="{{ question.url }}">{{ question.url }}</a>
            </div>
          </div>
          </div>
  </div>


  <h3>共有{{ question.answer_count }}个答案</h3>
    {% for answer in question.answers %}
        <div class="col s12 m6 z-depth-2">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <p>{{ answer.answer_text | safe }}</p>
            </div>
            <div class="card-action">
              {% if answer.is_accepted %}
                  <p>该答案已被采纳</p>
              {% endif %}
              <p>赞成数量{{ answer.answer_votes }}</p>
            </div>

          </div>
        </div>
    {% endfor %}

{% endblock %}

QADoorWebDjango/QADoorWebDjangoApp/templates/QADoorWebDjangoApp/index.html
{% extends "QADoorWebDjangoApp/base.html" %}
{% load staticfiles %}
{% load paginate_tags %}
{% load mongoid_tags %}

{% block content %}
<div>
    <table class="bordered highlight responsive-table">
        <thead>
            <tr>
                <th data-field="title">标题</th>
                <th data-field="tag">标签</th>
                <th data-field="count">状态</th>
            </tr>
        </thead>
        <tbody>
            {% if questions %}

            {% paginate questions 20 %}
            {% for q in questions %}
            <tr>
              <td>
                  <a href="{% url 'QADoorWebDjangoApp:detail' q|private:'_id' %}">{{q.title|safe}}</a>
                  <a id="q_detail" class="right hide-on-med-and-down" href="#{{ q|private:'_id' }}"><i class="material-icons left">info_outline</i></a>
                  <div id="{{ q|private:'_id' }}" class="modal">
                    <div class="modal-content">
                      <h4>问题详情</h4>
                      <p>{{ q.content|safe }}</p>
                    </div>
                    <div class="modal-footer">
                      <a href="{% url 'QADoorWebDjangoApp:detail' q|private:'_id' %}">查看答案</a>
                      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">关闭</a>
                    </div>
                  </div>
              </td>
              <td>
              {% for tag in q.tags %}
                  <div class="chip">
                    <a href="{% url 'QADoorWebDjangoApp:tag' tag %}">{{tag}}</a>
                  </div>
              {% endfor %}
              </td>

              <td>
                  {% if  q.is_solved %}
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="已解决">已解决</a>
                  {% else %}
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="未解决">未解决</a>
                  {% endif %}
                  <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="回答数量">{{q.answer_count}}</a>
                  <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="查看数量">{{q.view_count}}</a>
                  <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="赞同数量">{{q.vote_count}}</a>
              </td>
            </tr>
            {% endfor %}
            {% endif %}
        </tbody>
    </table>

    {% include 'QADoorWebDjangoApp/pagination.html' %}

</div>
    <script>
        $(document).ready(function(){
            // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
            $('.modal').modal();
        });
    </script>
{% endblock %}

QADoorWebDjango/QADoorWebDjangoApp/templates/QADoorWebDjangoApp/pagination.html
<ul class="pagination">
    {# 上一页 #}
    {% if questions.has_previous %}
        <li class="waves-effect"><a href="?page={{ questions.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
    {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    {% endif %}

    {% if first_page == current_page %}
        <li class="active"><a>1</a></li>
    {% else %}
        <li class="waves-effect"><a href="?page=1">1</a></li>
    {% endif %}

    {% if pages_first > 2 %}
        <li class="waves-effect"><a href="#">...</a></li>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <li class="active"><a>{{ page }}</a></li>
        {% else %}
            <li class="waves-effect"><a href="?page={{ page }}">{{ page }}</a></li>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <li class="waves-effect"><a href="#">...</a></li>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <li class="active"><a>{{ last_page }}</a></li>
        {% else %}
            <li class="waves-effect"><a href="?page={{ last_page }}">{{ last_page }}</a></li>
        {% endif %}
    {% endif %}

    {# 下一页 #}
    {% if questions.has_next %}
        <li class="waves-effect"><a href="?page={{ questions.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
    {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
    {% endif %}
</ul>