QADoorWeb/app/question/models.py
from app import db

class Questions(db.Document):

    _id = db.IntField(primary_key=True)
    url = db.URLField()
    title = db.StringField()
    content = db.StringField()
    is_solved = db.BooleanField(default=0)
    answer_count = db.IntField()
    view_count = db.StringField()
    vote_count = db.StringField()
    tags = db.ListField()
    answers = db.ListField()
    source = db.StringField()

QADoorWeb/app/__init__.py
from .qadoor_app import app
from .qadoor_db import db
from .question import Questions
from .question import question


app.register_blueprint(question)

QADoorWeb/app/question/__init__.py
from .models import Questions
from .views import question

QADoorWeb/app/question/views.py
from flask import Blueprint, render_template, url_for, request, flash, redirect, session, jsonify, current_app
from flask_login import current_user, login_required
from .models import Questions
from flask_mongoengine import Pagination

PER_PAGE = 20
question = Blueprint('question', __name__, url_prefix='')

@question.route('/', methods=['GET'])
@question.route('/<int:page>', methods=['GET'])
def question_index(page=1):
    # paginate = Questions.query.filter(Questions.id).paginate(page, PER_PAGE)
    pagination = Questions.objects.paginate(page=page, per_page=PER_PAGE)
    # return render_template('index.html', pagination=pagination)
    return render_template('index.html', questions=pagination.items, pagination=pagination)

@question.route('/search/', methods=['GET', 'POST'])
@question.route('/search/<string:keyword>/', methods=['GET', 'POST'])
@question.route('/search/<string:keyword>/<int:page>', methods=['GET', 'POST'])
def question_search(keyword='', page=1):
    # keyword = request.form['key']
    # keyword = request.form['key']
    print(keyword)
    questions = Questions.objects(title__icontains=keyword)
    pagination = Pagination(questions, page=page, per_page=PER_PAGE)
    return render_template('index.html', questions=pagination.items, pagination=pagination)

@question.route('/tag/<string:tag>/', methods=['GET'])
@question.route('/tag/<string:tag>/<int:page>', methods=['GET'])
def question_tag(tag, page=1):
    # paginate = Questions.query.filter(Questions.tags.like('%'+tag+'%')).paginate(page, PER_PAGE)
    questions = Questions.objects(tags=tag)
    pagination = Pagination(questions, page=page, per_page=PER_PAGE)
    return render_template('index.html', questions=pagination.items, pagination=pagination)

@question.route('/detail/<question_id>', methods=['GET'])
def question_detail(question_id):
    question = Questions.objects.get_or_404(_id=question_id)
    return render_template('question_detail.html', question=question)

@question.errorhandler(404)
def not_found(error):
    return render_template('404.html')

QADoorWeb/app/templates/index.html
{% extends "layout.html" %}

{% block content %}
<div>
    <table class="bordered highlight responsive-table">
        <thead>
            <tr>
                <th data-field="title">标题</th>
                <th data-field="tag">标签</th>
                <th data-field="count">状态</th>
            </tr>
        </thead>
        <tbody>
            {% if questions %}
            {% for q in questions %}
            <tr>
              <!--<td>
                  <ul class="collapsible" data-collapsible="accordion">
                    <li>
                      <div class="collapsible-header"><a href="{{ url_for('question.question_detail', question_id=q._id) }}">{{q.title|safe}}</a></div>
                      <div class="collapsible-body">
                          <div class="col s12 m6">
                              <div class="card blue-grey darken-1">
                                <div class="card-content white-text">
                                  <span class="card-title">问题详情</span>
                                  <p>{{ q.content|safe }}</p>
                                </div>
                                <div class="card-action">
                                  <a href="{{ url_for('question.question_detail', question_id=q._id) }}">查看答案</a>
                                </div>
                              </div>
                            </div>
                      </div>
                    </li>

                  </ul>
              </td>-->
              <td>
                  <a href="{{ url_for('question.question_detail', question_id=q._id) }}">{{q.title|safe}}</a>
                  <a id="q_detail" class="right hide-on-med-and-down" href="#{{ q._id }}"><i class="material-icons left">info_outline</i></a>
                  <div id="{{ q._id }}" class="modal">
                    <div class="modal-content">
                      <h4>问题详情</h4>
                      <p>{{ q.content|safe }}</p>
                    </div>
                    <div class="modal-footer">
                      <a href="{{ url_for('question.question_detail', question_id=q._id) }}">查看答案</a>
                      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">关闭</a>
                    </div>
                  </div>
              </td>
              <td>
              {% for tag in q.tags %}
                  <div class="chip">
                    <a href="{{ url_for('question.question_tag', tag=tag) }}">{{tag}}</a>
                  </div>
              {% endfor %}
              </td>

              <td>
                  {% if  q.is_solved %}
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="已解决">已解决</a>
                  {% else %}
                    <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="未解决">未解决</a>
                  {% endif %}
                  <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="回答数量">{{q.answer_count}}</a>
                  <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="查看数量">{{q.view_count}}</a>
                  <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="赞同数量">{{q.vote_count}}</a>
              </td>
            </tr>
            {% endfor %}
            {% endif %}
        </tbody>
    </table>


   <div class=pagination>
        {% if pagination.has_prev %}
            <li class="waves-effect"><a href="./{{ pagination.prev_num }}" >上一页</a></li>
        {% endif %}

        <li class="active"><strong><a href="">当前页 {{ pagination.page }} of {{ pagination.pages }}.</a></strong></li>

        {% if pagination.has_next %}
            <li class="waves-effect"><a href="./{{ pagination.next_num }}">下一页</a></li>
        {% endif %}
  </div>

</div>
    <script>
        $(document).ready(function(){
            // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
            $('.modal').modal();
        });
    </script>
{% endblock %}

QADoorWeb/app/templates/layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/materialize.min.css', _external=True )}}" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/jquery.min.js', _external=True )}}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/materialize.min.js', _external=True )}}"></script>

    <title>问答门</title>
</head>
<body>

    <nav>
        <div class="nav-wrapper">
          <a href="/" class="brand-logo"><img src="/static/img/logo.png"></a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li>
                <form id="search_form" class="col s12" action="" method="post">
                  <div class="row">
                    <div class="input-field col s6">
                      <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                      <input id="search" type="text" name="key" value="">
                    </div>
                  </div>
                </form>
              </li>
              <li><a href="/">问答</a></li>
              <li><a href="/">专栏</a></li>
              <li><a href="/">求职</a></li>
          </ul>
        </div>
    </nav>

    <div class="container">
         <div class="container">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
         </div>

         <div>
            {% block content %}
            {% endblock %}
         </div>

    </div>

    <footer class="page-footer">
      <div class="footer-copyright">
        <div class="container">
        © 2017 Copyright Jlan
        </div>
      </div>
    </footer>

    <script>
      $(document).ready(function() {
        $(".button-collapse").sideNav();
      });

      $(function() {
          $('#search').bind('input propertychange', function () {
              var $key = $("#search").val();
              $("#search_form").attr("action",'/search/'+$key+'/');
          })
      });
    </script>

</body>
</html>

QADoorWeb/app/templates/question_detail.html
{% extends "layout.html" %}

{% block content %}


  <div class="">
    <div class="col s12 m7">
      <div class="card">
        <div class="card-image">
          <img id="random_pic" src="" height="200">
          <span class="card-title">{{ question.title| safe }}</span>
        </div>
        <div class="card-content">
          <p>{{ question.content | safe }}</p>
        </div>
        <div class="card-action">
          来源：<a class="mdl-button" href="{{ question.url }}">{{ question.url }}</a>
        </div>
      </div>
    </div>
  </div>


  <h3>共有{{ question.answer_count }}个答案</h3>
    {% for answer in question.answers %}
        <div class="col s12 m6 z-depth-2">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <p>{{ answer.answer_text | safe }}</p>
            </div>
            <div class="card-action">
              {% if answer.is_accepted %}
                  <p>该答案已被采纳</p>
              {% endif %}
              <p>赞成数量{{ answer.answer_votes }}</p>
            </div>

          </div>
        </div>
    {% endfor %}


    <script>
        $(document).ready(function(){
            var index = Math.ceil(Math.random()*4+1);
            document.getElementById("random_pic").src="../static/img/random/"+index+".png";
        });
    </script>

{% endblock %}